/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BaseRouteRouteImport } from './routes/_base/route'
import { Route as BaseIndexRouteImport } from './routes/_base/index'
import { Route as ApiAuthFeishuSessionRouteImport } from './routes/api/auth/feishu/session'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRouteRoute = BaseRouteRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRouteRoute,
} as any)
const ApiAuthFeishuSessionRoute = ApiAuthFeishuSessionRouteImport.update({
  id: '/api/auth/feishu/session',
  path: '/api/auth/feishu/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseIndexRoute
  '/auth': typeof AuthRoute
  '/api/auth/feishu/session': typeof ApiAuthFeishuSessionRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof BaseIndexRoute
  '/api/auth/feishu/session': typeof ApiAuthFeishuSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_base': typeof BaseRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_base/': typeof BaseIndexRoute
  '/api/auth/feishu/session': typeof ApiAuthFeishuSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/api/auth/feishu/session'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/' | '/api/auth/feishu/session'
  id: '__root__' | '/_base' | '/auth' | '/_base/' | '/api/auth/feishu/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BaseRouteRoute: typeof BaseRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAuthFeishuSessionRoute: typeof ApiAuthFeishuSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRouteRoute
    }
    '/api/auth/feishu/session': {
      id: '/api/auth/feishu/session'
      path: '/api/auth/feishu/session'
      fullPath: '/api/auth/feishu/session'
      preLoaderRoute: typeof ApiAuthFeishuSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BaseRouteRouteChildren {
  BaseIndexRoute: typeof BaseIndexRoute
}

const BaseRouteRouteChildren: BaseRouteRouteChildren = {
  BaseIndexRoute: BaseIndexRoute,
}

const BaseRouteRouteWithChildren = BaseRouteRoute._addFileChildren(
  BaseRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BaseRouteRoute: BaseRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAuthFeishuSessionRoute: ApiAuthFeishuSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './app/router/index.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
